# Generated by Django 5.0.14 on 2026-02-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Post 1, USTA 1', max_length=50)),
                ('slug', models.SlugField(help_text='URL friendly name, e.g., post-1', unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='The static IP of the laptop (e.g., 192.168.1.101)', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Sequence order (№)')),
                ('description', models.TextField(help_text='Описание работ')),
                ('part_number', models.CharField(blank=True, help_text='Обозначение', max_length=100)),
                ('part_name', models.CharField(blank=True, help_text='Наименование', max_length=200)),
                ('quantity', models.CharField(blank=True, help_text='Кол.', max_length=20)),
                ('tooling', models.CharField(blank=True, help_text='Оснастка (Keys, etc.)', max_length=200)),
                ('torque', models.CharField(blank=True, help_text='Момент затяжки', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='steps/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.productvariant')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workstation')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
