# Generated by Django 5.0.14 on 2026-02-14 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assemblystep',
            unique_together={('workstation', 'product', 'step_number')},
        ),
        migrations.AddField(
            model_name='assemblystep',
            name='standard_duration_seconds',
            field=models.IntegerField(default=300, help_text='Time allowed in seconds'),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='step_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='tooling',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='torque',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='TruckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productvariant')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workstation')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(choices=[('USTA_1', 'Usta 1'), ('USTA_2', 'Usta 2'), ('BRIGADIR', 'Brigadir')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('was_intervened', models.BooleanField(default=False, help_text='True if Brigadier took over')),
                ('assembly_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assemblystep')),
                ('truck_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.truckrun')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='assemblystep',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='assemblystep',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='assemblystep',
            name='quantity',
        ),
    ]
