# Generated by Django 5.0.14 on 2026-02-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assemblystep_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'ordering': ['ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='assemblystep',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='operator_id',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='status_color',
            field=models.CharField(blank=True, choices=[('GREEN', 'On Time'), ('YELLOW', 'Late'), ('RED', 'Very Late / Issue')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workstation',
            name='reset_pin',
            field=models.CharField(default='1234', help_text='PIN to reset the truck', max_length=4),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productvariant'),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='standard_duration_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workstation'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='was_intervened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assemblystep',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.taskcategory'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('USTA', 'Operator'), ('BRIGADIR', 'Brigadier')], default='USTA', max_length=20)),
                ('assigned_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workstation')),
            ],
        ),
        migrations.AddField(
            model_name='tasklog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker'),
        ),
    ]
