# Generated by Django 5.0.14 on 2026-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskcategory_remove_assemblystep_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trucks/'),
        ),
        migrations.AddField(
            model_name='truckrun',
            name='truck_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
