# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productvariant_image_truckrun_truck_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrun',
            name='truck_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
