# Generated by Django 5.0.14 on 2026-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_truckrun_truck_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
