# Generated by Django 5.0.14 on 2026-03-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_part_inventory_partconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('assembly_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_parts', to='core.assemblystep')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.part')),
            ],
        ),
    ]
