# Generated by Django 5.0.14 on 2026-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_steppart'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='critical_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='inventory',
            name='low_level',
            field=models.IntegerField(default=5),
        ),
    ]
