# Generated by Django 5.0.14 on 2026-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='part',
            name='reorder_quantity',
            field=models.IntegerField(default=20),
        ),
    ]
