# Generated by Django 5.0.14 on 2026-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_worker_role_productionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckrun',
            name='current_station',
            field=models.IntegerField(default=1),
        ),
    ]
