# Generated by Django 5.0.14 on 2026-03-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_truckrun_current_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrun',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workstation'),
        ),
    ]
