# Generated by Django 5.0.14 on 2026-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_truckrun_workstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='status',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='tractor_image',
            field=models.ImageField(blank=True, null=True, upload_to='tractors/'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='vin_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truckrun',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='truckrun',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='truckrun',
            name='truck_serial_number',
            field=models.CharField(default='old', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
