# Generated by Django 5.0.14 on 2026-03-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_productionorder_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assemblystep',
            unique_together={('workstation', 'step_number')},
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariant'),
        ),
    ]
