# Generated by Django 5.0.14 on 2026-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_product_worker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True, verbose_name='Цифровой отпечаток лица'),
        ),
    ]
