# Generated by Django 5.0.14 on 2026-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_worker_face_descriptor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblystep',
            options={'ordering': ['product', 'step_number'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания (Техкарты)'},
        ),
        migrations.AlterUniqueTogether(
            name='assemblystep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assemblystep',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (например: 1.1 Установка...)'),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='description',
            field=models.TextField(verbose_name='Описание работ'),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='standard_duration_seconds',
            field=models.IntegerField(default=300, verbose_name='Время (сек)'),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='step_number',
            field=models.IntegerField(verbose_name='№ шага'),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='tooling',
            field=models.CharField(blank=True, max_length=200, verbose_name='Оснастка'),
        ),
        migrations.AlterField(
            model_name='assemblystep',
            name='torque',
            field=models.CharField(blank=True, max_length=50, verbose_name='Момент затяжки'),
        ),
        migrations.AlterUniqueTogether(
            name='assemblystep',
            unique_together={('product', 'workstation', 'step_number')},
        ),
    ]
