# Generated by Django 5.0.14 on 2026-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_assemblystep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_substitute',
            field=models.BooleanField(default=False, verbose_name='Рабочий на замену (скрыть из списка станции)'),
        ),
    ]
