# Generated by Django 5.0.14 on 2026-03-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_worker_is_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='substituted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituting_for', to='core.worker', verbose_name='Кем заменен в данный момент'),
        ),
    ]
