# Generated by Django 5.0.14 on 2026-03-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_worker_substituted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppart',
            name='package_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='№ пакета'),
        ),
    ]
