# Generated by Django 5.0.14 on 2026-03-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_steppart_package_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckrun',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'В процессе сборки'), ('REWORK', 'На доработке (Брак)'), ('COMPLETED', 'Сборка завершена')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MECH', 'Механический дефект (резьба, металл)'), ('ELEC', 'Электрика (проводка, контакты)'), ('PAINT', 'Покраска / Царапины'), ('PART_MISSING', 'Нехватка детали / Недокомплект'), ('PART_DEFECT', 'Брак самой детали'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание дефекта (текст)')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Критический (Блокирует конвейер)')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Исправлено')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обнаружения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время устранения')),
                ('assembly_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assemblystep', verbose_name='Шаг сборки')),
                ('truck_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='core.truckrun', verbose_name='Трактор (VIN)')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Журнал дефектов',
                'verbose_name_plural': 'Журнал дефектов',
                'ordering': ['-reported_at'],
            },
        ),
    ]
