# Generated by Django 5.0.14 on 2026-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_truckrun_status_defectlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
